trigger:
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - script: echo Build my project here

- stage: Deploy
  job: DeployJob
  steps:
  - script: echo Deploy steps go here
  - task: TerraformCLI@0
    inputs:
      command: 'apply'
      workingDirectory: '$(System.DefaultWorkingDirectory)'
      environmentServiceName: 'yourServiceConnection'
